In [38]:
#import and authenticate plotly, a graphing library
import plotly
plotly.tools.set_credentials_file(username='wr2299', api_key='oraDkpMv12Ym7uqQkKrS')

import plotly.plotly as py
import plotly.graph_objs as go

In [39]:
#import pandas to handle the reading of raw data
import pandas

prescriptionsTable = pandas.read_table("two.tsv")

prescriptionsTable

,State,State Code,Number of Scripts / 100 people,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,Unnamed: 14,AVERAGE:
0,Alabama,AL,NaN,115.600,120.300,126.100,131.600,134.300,136.60,143.800,142.400,135.200,125.000,121.000,NaN,130.173
1,Alaska,AK,NaN,63.400,66.600,68.500,67.300,68.400,68.00,66.800,63.700,62.700,60.800,58.900,NaN,65.009
2,Arizona,AZ,NaN,74.300,77.800,80.900,84.200,88.500,88.60,85.300,80.400,79.700,75.500,70.200,NaN,80.491
3,Arkansas,AR,NaN,98.300,108.200,112.100,116.000,120.800,115.20,121.800,120.900,123.200,117.200,114.600,NaN,115.300
4,California,CA,NaN,51.000,53.600,55.100,55.600,55.800,55.90,56.400,54.400,52.700,47.700,44.800,NaN,53.000
5,Colorado,CO,NaN,62.200,65.900,67.700,69.800,72.000,73.00,73.500,71.200,69.600,65.100,59.800,NaN,68.164
6,Connecticut,CT,NaN,64.700,67.500,68.700,68.100,68.600,69.10,69.300,67.400,66.000,62.300,55.900,NaN,66.145
7,Delaware,DE,NaN,86.600,92.300,95.400,97.500,101.100,99.70,94.000,92.700,91.000,84.400,79.200,NaN,92.173
8,District of Columbia,DC,NaN,31.700,41.200,34.500,34.400,37.100,39.80,40.300,41.100,40.100,35.700,32.500,NaN,37.127
9,Florida,FL,NaN,79.700,82.200,84.300,86.300,87.600,83.50,75.900,73.500,71.400,67.100,66.600,NaN,78.009
10,Georgia,GA,NaN,79.800,82.500,86.300,88.200,90.200,88.60,89.400,86.600,83.800,79.400,77.800,NaN,84.782
11,Hawaii,HI,NaN,42.300,44.500,46.600,47.800,50.100,50.10,50.400,49.400,47.700,44.300,41.900,NaN,46.827
12,Idaho,ID,NaN,75.600,78.800,82.700,85.200,88.600,91.40,92.000,89.200,87.400,81.900,77.600,NaN,84.582
13,Illinois,IL,NaN,55.600,59.200,60.200,61.000,63.100,64.30,66.100,63.700,62.300,59.100,56.800,NaN,61.036
14,Indiana,IN,NaN,94.300,99.700,103.300,105.600,107.100,106.70,110.500,106.300,96.700,89.100,83.900,NaN,100.291
15,Iowa,IA,NaN,59.300,57.100,59.100,60.400,62.300,64.00,74.100,72.200,72.300,68.600,64.000,NaN,64.855
16,Kansas,KS,NaN,77.500,80.600,82.700,82.800,86.100,87.80,90.300,88.700,86.500,80.500,76.900,NaN,83.673
17,Kentucky,KY,NaN,122.600,130.800,136.600,135.200,136.500,137.00,127.900,111.700,110.000,102.600,97.200,NaN,122.555
18,Louisiana,LA,NaN,109.200,110.100,113.700,113.000,112.600,111.70,113.000,112.400,108.900,100.400,98.100,NaN,109.373
19,Maine,ME,NaN,83.600,85.400,88.700,87.900,92.800,93.10,89.700,85.900,82.400,76.500,66.900,NaN,84.809
20,Maryland,MD,NaN,60.100,63.300,65.500,66.900,71.200,72.90,72.200,69.000,67.600,63.000,58.700,NaN,66.400
21,Massachusetts,MA,NaN,66.000,68.200,69.200,68.900,67.900,65.90,65.700,63.000,59.600,54.000,47.100,NaN,63.227
22,Michigan,MI,NaN,80.200,85.600,89.900,91.600,96.000,98.80,100.700,98.900,98.000,90.500,84.900,NaN,92.282
23,Minnesota,MN,NaN,50.300,53.700,56.500,58.600,59.000,60.00,60.900,58.300,56.600,52.100,46.900,NaN,55.718
24,Mississippi,MS,NaN,102.700,109.900,113.200,117.300,118.100,117.20,121.800,119.600,116.300,110.900,105.600,NaN,113.873
25,Missouri,MO,NaN,80.500,84.300,86.800,88.500,91.000,91.60,95.400,93.300,90.700,84.500,80.400,NaN,87.909
26,Montana,MT,NaN,79.100,81.100,85.300,85.800,87.200,85.30,87.700,84.200,80.100,73.300,69.800,NaN,81.718
27,Nebraska,NE,NaN,64.300,65.100,66.200,66.400,69.000,68.80,73.200,71.300,70.100,65.500,62.800,NaN,67.518
28,Nevada,NV,NaN,87.700,90.200,97.000,94.000,97.300,100.30,98.900,91.100,90.100,85.400,80.700,NaN,92.064
29,New Hampshire,NH,NaN,75.000,78.500,81.700,81.500,81.600,80.90,83.700,82.000,79.600,74.800,64.300,NaN,78.509
30,New Jersey,NJ,NaN,54.700,57.200,59.500,59.900,61.000,61.50,60.100,58.300,57.200,56.000,52.600,NaN,58.000
31,New Mexico,NM,NaN,61.800,69.000,71.400,75.300,81.900,81.60,76.800,71.400,71.500,69.800,65.100,NaN,72.327
32,New York,NY,NaN,44.200,46.100,48.400,49.500,51.000,51.10,51.800,46.700,43.900,45.100,42.700,NaN,47.318
33,North Carolina,NC,NaN,85.200,87.500,88.600,89.300,93.100,93.50,98.600,96.700,93.700,88.400,82.500,NaN,90.645
34,North Dakota,ND,NaN,56.000,59.300,61.700,60.300,63.000,61.30,62.100,60.100,58.100,53.000,47.800,NaN,58.427
35,Ohio,OH,NaN,87.700,92.700,97.500,100.400,102.400,101.50,97.500,93.100,89.500,82.700,75.300,NaN,92.755
36,Oklahoma,OK,NaN,108.700,114.400,111.300,115.000,119.600,122.30,127.400,123.300,110.900,104.400,97.900,NaN,114.109
37,Oregon,OR,NaN,91.000,95.500,99.100,99.300,101.200,100.70,98.700,94.200,91.900,84.200,76.300,NaN,93.827
38,Pennsylvania,PA,NaN,69.500,73.700,76.500,78.100,81.000,81.70,83.300,81.600,79.900,75.500,69.500,NaN,77.300
39,Rhode Island,RI,NaN,78.700,82.200,82.900,82.500,82.700,82.50,83.200,76.900,72.800,65.700,60.300,NaN,77.309
40,South Carolina,SC,NaN,90.400,91.700,94.100,95.800,98.600,96.80,104.000,103.000,101.300,95.100,89.400,NaN,96.382
41,South Dakota,SD,NaN,50.000,49.900,52.100,52.300,54.000,55.10,60.100,60.600,61.700,59.100,54.800,NaN,55.427
42,Tennessee,TN,NaN,124.800,128.800,132.900,138.400,140.000,138.50,136.100,127.100,121.300,114.900,107.500,NaN,128.209
43,Texas,TX,NaN,66.800,71.200,71.300,71.800,73.000,72.00,73.400,70.000,67.000,59.800,57.600,NaN,68.536
44,Utah,UT,NaN,87.000,89.800,91.300,86.900,86.600,85.20,84.500,82.100,78.800,74.400,70.400,NaN,83.364
45,Vermont,VT,NaN,56.900,56.000,56.500,54.500,54.100,53.60,54.600,52.200,50.400,60.100,58.600,NaN,55.227
46,Virginia,VA,NaN,67.200,70.100,73.000,74.100,75.500,76.60,79.600,76.600,73.500,68.100,63.400,NaN,72.518
47,Washington,WA,NaN,80.800,84.400,86.600,86.100,85.000,81.60,78.700,75.200,74.200,69.800,64.900,NaN,78.845
48,West Virginia,WV,NaN,129.900,135.100,145.500,146.900,143.100,139.60,136.900,129.000,126.400,111.300,96.000,NaN,130.882
49,Wisconsin,WI,NaN,64.700,69.200,70.600,71.900,74.400,75.20,76.800,73.800,71.900,67.500,62.200,NaN,70.745
50,Wyoming,WY,NaN,79.900,80.800,81.000,81.000,80.400,78.20,80.500,81.500,80.900,75.400,71.100,NaN,79.155
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,AVERAGE:,NaN,NaN,76.649,80.173,82.673,83.661,85.559,85.41,86.184,83.096,80.688,75.637,70.818,NaN,NaN

In [40]:
#import pandas to handle the reading of raw data
import pandas

deathsTable = pandas.read_table("three.txt")

deathsTable

,Notes,Year,Year Code,State,State Code,Deaths,Population,Crude Rate
0,NaN,2006,2006,Alabama,1.0,223,4628981,4.8
1,NaN,2006,2006,Alaska,2.0,82,675302,12.1
2,NaN,2006,2006,Arizona,4.0,539,6029141,8.9
3,NaN,2006,2006,Arkansas,5.0,224,2821761,7.9
4,NaN,2006,2006,California,6.0,3602,36021202,10.0
5,NaN,2006,2006,Colorado,8.0,444,4720423,9.4
6,NaN,2006,2006,Connecticut,9.0,238,3517460,6.8
7,NaN,2006,2006,Delaware,10.0,76,859268,8.8
8,NaN,2006,2006,District of Columbia,11.0,85,570681,14.9
9,NaN,2006,2006,Florida,12.0,1951,18166990,10.7
10,NaN,2006,2006,Georgia,13.0,520,9155813,5.7
11,NaN,2006,2006,Hawaii,15.0,148,1309731,11.3
12,NaN,2006,2006,Idaho,16.0,125,1468669,8.5
13,NaN,2006,2006,Illinois,17.0,698,12643955,5.5
14,NaN,2006,2006,Indiana,18.0,329,6332669,5.2
15,NaN,2006,2006,Iowa,19.0,254,2982644,8.5
16,NaN,2006,2006,Kansas,20.0,263,2762931,9.5
17,NaN,2006,2006,Kentucky,21.0,364,4219239,8.6
18,NaN,2006,2006,Louisiana,22.0,222,4302665,5.2
19,NaN,2006,2006,Maine,23.0,150,1323619,11.3
20,NaN,2006,2006,Maryland,24.0,384,5627367,6.8
21,NaN,2006,2006,Massachusetts,25.0,371,6410084,5.8
22,NaN,2006,2006,Michigan,26.0,788,10036081,7.9
23,NaN,2006,2006,Minnesota,27.0,535,5163555,10.4
24,NaN,2006,2006,Mississippi,28.0,128,2904978,4.4
25,NaN,2006,2006,Missouri,29.0,543,5842704,9.3
26,NaN,2006,2006,Montana,30.0,124,952692,13.0
27,NaN,2006,2006,Nebraska,31.0,112,1772693,6.3
28,NaN,2006,2006,Nevada,32.0,368,2522658,14.6
29,NaN,2006,2006,New Hampshire,33.0,122,1308389,9.3
...,...,...,...,...,...,...,...,...
490,NaN,2015,2015,Michigan,26.0,950,9922576,9.6
491,NaN,2015,2015,Minnesota,27.0,630,5489594,11.5
492,NaN,2015,2015,Mississippi,28.0,191,2992333,6.4
493,NaN,2015,2015,Missouri,29.0,773,6083672,12.7
494,NaN,2015,2015,Montana,30.0,170,1032949,16.5
495,NaN,2015,2015,Nebraska,31.0,131,1896190,6.9
496,NaN,2015,2015,Nevada,32.0,495,2890845,17.1
497,NaN,2015,2015,New Hampshire,33.0,188,1330608,14.1
498,NaN,2015,2015,New Jersey,34.0,593,8958013,6.6
499,NaN,2015,2015,New Mexico,35.0,325,2085109,15.6
500,NaN,2015,2015,New York,36.0,1917,19795791,9.7
501,NaN,2015,2015,North Carolina,37.0,1322,10042802,13.2
502,NaN,2015,2015,North Dakota,38.0,113,756927,14.9
503,NaN,2015,2015,Ohio,39.0,1544,11613423,13.3
504,NaN,2015,2015,Oklahoma,40.0,555,3911338,14.2
505,NaN,2015,2015,Oregon,41.0,828,4028977,20.6
506,NaN,2015,2015,Pennsylvania,42.0,1014,12802503,7.9
507,NaN,2015,2015,Rhode Island,44.0,250,1056298,23.7
508,NaN,2015,2015,South Carolina,45.0,631,4896146,12.9
509,NaN,2015,2015,South Dakota,46.0,77,858469,9.0
510,NaN,2015,2015,Tennessee,47.0,1123,6600299,17.0
511,NaN,2015,2015,Texas,48.0,1814,27469114,6.6
512,NaN,2015,2015,Utah,49.0,592,2995919,19.8
513,NaN,2015,2015,Vermont,50.0,109,626042,17.4
514,NaN,2015,2015,Virginia,51.0,793,8382993,9.5
515,NaN,2015,2015,Washington,53.0,1028,7170351,14.3
516,NaN,2015,2015,West Virginia,54.0,668,1844128,36.2
517,NaN,2015,2015,Wisconsin,55.0,723,5771337,12.5
518,NaN,2015,2015,Wyoming,56.0,84,586107,14.3
519,Total,2015,2015,NaN,NaN,34766,321418820,10.8

In [41]:
#import necessary graphing libraries
import plotly.graph_objs as go
import plotly.plotly as py

#include year array
year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


#prescriptions array from raw data
stateInfo = prescriptionsTable.loc[0]

statePrescriptions = stateInfo[3:14]

statePrescriptions



#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[0 + x*52]]

deathsFinal



# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
)

trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Alabama')

In [42]:
#import necessary graphing libraries
import plotly.graph_objs as go
import plotly.plotly as py

#include year array
year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[1]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[1 + x*52]]

deathsFinal




# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Alaska')

In [43]:
#import necessary graphing libraries
import plotly.graph_objs as go
import plotly.plotly as py

#include year array
year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[2]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[2 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Arizona')

In [44]:
#import necessary graphing libraries
import plotly.graph_objs as go
import plotly.plotly as py

#include year array
year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[3]

statePrescriptions = stateInfo[3:14]

statePrescriptions



#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[3 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Arkansas')

In [45]:
#import necessary graphing libraries
import plotly.graph_objs as go
import plotly.plotly as py

#include year array
year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[4]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[4 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='California')

In [46]:
#import necessary graphing libraries
import plotly.graph_objs as go
import plotly.plotly as py

#include year array
year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[5]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[5 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Colorado')

In [47]:
 
# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[6]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[6 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Connecticut')

In [48]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[7]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[7 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Delaware')

In [49]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[8]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[8 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='District of Columbia')

In [50]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[9]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[9 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Florida')

In [51]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[10]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[10 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Georgia')

In [52]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[11]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[11 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Hawaii')

In [53]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[12]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[12 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Idaho')

In [54]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[13]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[13 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Illinois')

In [55]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[14]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[14 + x*52]]

deathsFinal



# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Indiana')

In [56]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[15]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[15 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)
#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Iowa')

In [57]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[16]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[16 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Kansas')

In [58]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[17]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[17 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Kentucky')

In [59]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[18]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[18 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Louisiana')

In [60]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[19]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[19 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Maine')

In [61]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[20]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[20 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Maryland')

In [66]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[21]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[21 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

#store traces for graphing
data = [trace, trace1]

#display graph
py.iplot(data, filename='Massachussetts')

In [64]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[22]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[22 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Michigan')

PlotlyRequestError: Account limit reached: Your account is limited to creating 25 charts. To continue, you can override or delete existing charts or you can upgrade your account at: https://plot.ly/products/cloud

In [65]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[23]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[23 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Minnesota')

PlotlyRequestError: Account limit reached: Your account is limited to creating 25 charts. To continue, you can override or delete existing charts or you can upgrade your account at: https://plot.ly/products/cloud

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[24]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[24 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Mississippi')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[25]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[25 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Montana')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[26]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[26 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Nebraska')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[27]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[27 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)
#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Nebraska')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[28]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[28 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Nevada')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[29]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[29 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='New Hampshire')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[30]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[30 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='New Jersey')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[31]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[31 + x*52]]

deathsFinal
# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='New Mexico')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[32]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[32 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='New York')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[33]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[33 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='North Carolina')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[34]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[34 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='North Dakota')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[35]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[35 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]
py.iplot(data, filename='Ohio')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[41]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[41 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='South Dakota')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[36]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[36 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Oklahoma')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[37]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[37 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Oregon')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[38]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[38 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Pennsylvania')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[39]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[39 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Rhode Island')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[40]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[40 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='South Carolina')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[42]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[42 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Tennessee')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[43]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[43 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Texas')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[44]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[44 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Utah')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[45]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[45 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Vermont')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[46]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[46 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Virginia')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[47]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[47 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Washington')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[48]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[48 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='West Virginia')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[49]

statePrescriptions = stateInfo[3:14]

statePrescriptions

#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[49 + x*52]]

deathsFinal


# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Wisconsin')

In [ ]:

# Create random data with numpy
import numpy as np

year = ['2006', '2007', '2008', '2009', '2010', '2011', '2012',
         '2013', '2014', '2015', '2016',]


stateInfo = prescriptionsTable.loc[50]

statePrescriptions = stateInfo[3:14]

statePrescriptions


#deaths array
stateDeath = deathsTable['Crude Rate']

deathsFinal = []

for x in range(9): 
    deathsFinal = deathsFinal + [stateDeath.loc[50 + x*52]]

deathsFinal

# Create a trace
trace = go.Scatter(
    x = year,
    y = statePrescriptions,
    name = 'state prescriptions'
    
)

#crude death rate plot
trace1 = go.Scatter(
    x = year,
    y = deathsFinal,
    name = 'deaths'
)

data = [trace, trace1]

py.iplot(data, filename='Wyoming')